project: demo
server:
  port: 8080

spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  cache:
    ehcache:
      config: ehcache.xml

---
#dev
spring:
  profiles: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.196.128:3306/demo?characterEncoding=utf-8&useSSL=false
log:
  path: /tmp/logs
  level: debug


---
#test
spring:
  profiles: test
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.196.128:3306/demo?characterEncoding=utf-8&useSSL=false
log:
  path: /tmp/logs
  level: debug


---
#prod