project: demo
server:
  context-path: /api/v1
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

---
#dev
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.196.128:3306/demo?characterEncoding=utf-8&useSSL=false
log:
  path: /tmp/logs
  level: debug
---
#test


---
#prod